import jsPDF from "jspdf";
import type { AnalysisResult } from "@/types";

export function exportMeasurementsPdf(
  result: AnalysisResult,
  filename = "room-analysis",
) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const margin = 20;
  const pageWidth = 210;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  doc.setFillColor(10, 10, 10);
  doc.rect(0, 0, pageWidth, 297, "F");
  doc.setTextColor(232, 232, 232);

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("INTERIOR ANALYZER", margin, y + 8);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 140, 174);
  doc.text("VITRUVI AI — SPATIAL ANALYSIS REPORT", margin, y + 16);
  doc.text(
    new Date().toLocaleDateString("en-GB", {
      day: "2-digit",
      month: "long",
      year: "numeric",
    }),
    pageWidth - margin,
    y + 16,
    { align: "right" },
  );

  y += 30;

  doc.setDrawColor(107, 140, 174);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(232, 232, 232);
  doc.text(result.roomType.toUpperCase(), margin, y);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 140, 174);
  doc.text(`CONFIDENCE: ${result.overallConfidence.toUpperCase()}`, pageWidth - margin, y, {
    align: "right",
  });
  y += 12;

  doc.setFontSize(8);
  doc.setTextColor(107, 140, 174);
  doc.text("DIMENSIONS", margin, y);
  y += 5;

  const dims: [string, string][] = [
    ["Length", result.dimensions.length],
    ["Width", result.dimensions.width],
    ["Ceiling Height", result.dimensions.height],
    ["Floor Area", result.dimensions.floorArea],
  ];

  dims.forEach(([label, value]) => {
    doc.setFillColor(26, 26, 26);
    doc.roundedRect(margin, y, contentWidth, 8, 1, 1, "F");
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(8);
    doc.text(label, margin + 3, y + 5.5);
    doc.setTextColor(232, 232, 232);
    doc.setFont("helvetica", "bold");
    doc.text(value, pageWidth - margin - 3, y + 5.5, { align: "right" });
    doc.setFont("helvetica", "normal");
    y += 10;
  });

  y += 6;

  doc.setFontSize(8);
  doc.setTextColor(107, 140, 174);
  doc.text("DETECTED OBJECTS", margin, y);
  y += 5;

  doc.setFillColor(34, 34, 34);
  doc.rect(margin, y, contentWidth, 7, "F");
  doc.setTextColor(107, 140, 174);
  doc.setFontSize(7);
  doc.text("OBJECT", margin + 3, y + 5);
  doc.text("EST. SIZE", margin + contentWidth * 0.55, y + 5);
  doc.text("CONFIDENCE", margin + contentWidth * 0.8, y + 5);
  y += 8;

  result.detectedObjects.forEach((obj, i) => {
    if (y > 260) {
      doc.addPage();
      doc.setFillColor(10, 10, 10);
      doc.rect(0, 0, pageWidth, 297, "F");
      y = margin;
    }
    if (i % 2 === 0) {
      doc.setFillColor(20, 20, 20);
      doc.rect(margin, y - 1, contentWidth, 7, "F");
    }
    doc.setTextColor(232, 232, 232);
    doc.setFontSize(8);
    doc.text(obj.name, margin + 3, y + 4);
    doc.setTextColor(150, 150, 150);
    doc.text(obj.estimatedSize, margin + contentWidth * 0.55, y + 4);
    const confColor =
      obj.confidence === "high"
        ? [82, 168, 130]
        : obj.confidence === "medium"
          ? [212, 168, 83]
          : [224, 82, 82];
    doc.setTextColor(...(confColor as [number, number, number]));
    doc.text(obj.confidence.toUpperCase(), margin + contentWidth * 0.8, y + 4);
    y += 7;
  });

  y += 8;

  if (result.notes) {
    doc.setFontSize(8);
    doc.setTextColor(107, 140, 174);
    doc.text("NOTES", margin, y);
    y += 5;
    doc.setTextColor(150, 150, 150);
    const lines = doc.splitTextToSize(result.notes, contentWidth - 6);
    doc.setFillColor(26, 26, 26);
    doc.roundedRect(margin, y, contentWidth, lines.length * 5 + 6, 1, 1, "F");
    doc.text(lines, margin + 3, y + 5);
  }

  doc.setFontSize(7);
  doc.setTextColor(60, 60, 60);
  doc.text(
    "Generated by Vitruvi AI Interior Analyzer · Estimates only — verify with physical measurement before construction",
    pageWidth / 2,
    287,
    { align: "center" },
  );

  doc.save(`${filename}-${Date.now()}.pdf`);
}
